<strong>Project</strong>: fabric-sdk-py<br><strong>Branch</strong>: master<br><strong>ID</strong>: 19849<br><strong>Subject</strong>: [FAB-9106]Correct several invalid URLs in docs.<br><strong>Status</strong>: ABANDONED<br><strong>Owner</strong>: Yumin Zheng - zhengyumin529@gmail.com<br><strong>Assignee</strong>:<br><strong>Created</strong>: 3/28/2018, 1:47:54 AM<br><strong>LastUpdated</strong>: 4/18/2019, 9:08:15 AM<br><strong>CommitMessage</strong>:<br><pre>[FAB-9106]Correct several invalid URLs in docs.

Change-Id: Iebfcdda6a7194bcea736d669ef3f480251a893a6
Signed-off-by: Szym29 <zhengyumin529@gmail.com>
</pre><h1>Comments</h1><strong>Reviewer</strong>: Yumin Zheng - zhengyumin529@gmail.com<br><strong>Reviewed</strong>: 3/28/2018, 1:47:54 AM<br><strong>Message</strong>: <pre>Uploaded patch set 1.</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 3/28/2018, 1:53:01 AM<br><strong>Message</strong>: <pre>Patch Set 1:

Build Started https://jenkins.hyperledger.org/job/fabric-sdk-py-verify-x86_64/406/</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 3/28/2018, 2:02:29 AM<br><strong>Message</strong>: <pre>Patch Set 1: Verified-1

Build Failed 

https://jenkins.hyperledger.org/job/fabric-sdk-py-verify-x86_64/406/ : FAILURE

No problems were identified. If you know why this problem occurred, please add a suitable Cause for it. ( https://jenkins.hyperledger.org/job/fabric-sdk-py-verify-x86_64/406/ )

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-sdk-py-verify-x86_64/406</pre><strong>Reviewer</strong>: Kai Chen - 281165273@qq.com<br><strong>Reviewed</strong>: 3/28/2018, 10:09:05 PM<br><strong>Message</strong>: <pre>Patch Set 1:

reverify</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 3/28/2018, 10:10:44 PM<br><strong>Message</strong>: <pre>Patch Set 1: -Verified

Build Started https://jenkins.hyperledger.org/job/fabric-sdk-py-verify-x86_64/407/</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 3/28/2018, 10:19:49 PM<br><strong>Message</strong>: <pre>Patch Set 1: Verified-1

Build Failed 

https://jenkins.hyperledger.org/job/fabric-sdk-py-verify-x86_64/407/ : FAILURE

No problems were identified. If you know why this problem occurred, please add a suitable Cause for it. ( https://jenkins.hyperledger.org/job/fabric-sdk-py-verify-x86_64/407/ )

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-sdk-py-verify-x86_64/407</pre><strong>Reviewer</strong>: Baohua Yang - yangbaohua@gmail.com<br><strong>Reviewed</strong>: 7/29/2018, 10:02:44 AM<br><strong>Message</strong>: <pre>Patch Set 1:

@yuming will u fix the CI errors?</pre><strong>Reviewer</strong>: Baohua Yang - yangbaohua@gmail.com<br><strong>Reviewed</strong>: 4/18/2019, 9:08:15 AM<br><strong>Message</strong>: <pre>Abandoned

Not active for quite a while, abandon first.</pre><h1>PatchSets</h1><h3>PatchSet Number: 1</h3><blockquote><strong>Type</strong>: REWORK<br><strong>Author</strong>: Yumin Zheng - zhengyumin529@gmail.com<br><strong>Uploader</strong>: Yumin Zheng - zhengyumin529@gmail.com<br><strong>Created</strong>: 3/28/2018, 1:47:54 AM<br><strong>UnmergedRevision</strong>: [77f6dcf26b2eb6bdb3cf60a5573cb504e6e05250](https://github.com/hyperledger-gerrit-archive/fabric-sdk-py/commit/77f6dcf26b2eb6bdb3cf60a5573cb504e6e05250)<br><br><strong>Approver</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Approved</strong>: 3/28/2018, 10:19:49 PM<br><strong>Type</strong>: Verified<br><strong>Value</strong>: -1<br><br></blockquote>