<strong>Project</strong>: fabric-sdk-java<br><strong>Branch</strong>: master<br><strong>ID</strong>: 34039<br><strong>Subject</strong>: [FABJ-496] Fix discoverEndorderEndpoints() errors<br><strong>Status</strong>: ABANDONED<br><strong>Owner</strong>: Nao Nishijima - nao.nishijima.xt@hitachi.com<br><strong>Assignee</strong>:<br><strong>Created</strong>: 10/21/2019, 12:06:01 PM<br><strong>LastUpdated</strong>: 10/23/2019, 8:21:39 AM<br><strong>CommitMessage</strong>:<br><pre>[FABJ-496] Fix discoverEndorderEndpoints() errors

This CR deletes serviceDiscoveryException clears. the variable is
clear at every loop. So the variable doesn't keep there an error
even if an error happens. If an error happens at the last loop,
it calls exceptions.

FABJ-496 #done

Signed-off-by: Nao Nishijima <nao.nishijima.xt@hitachi.com>
Change-Id: I8528920f25dfe3943d161141d782ee70817deb5b
</pre><h1>Comments</h1><strong>Reviewer</strong>: Nao Nishijima - nao.nishijima.xt@hitachi.com<br><strong>Reviewed</strong>: 10/21/2019, 12:06:01 PM<br><strong>Message</strong>: <pre>Uploaded patch set 1.</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 10/21/2019, 12:09:28 PM<br><strong>Message</strong>: <pre>Patch Set 1:

Build Started https://jenkins.hyperledger.org/job/fabric-sdk-java-master-verify-1.4-x86_64/217/ (1/2)</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 10/21/2019, 12:10:16 PM<br><strong>Message</strong>: <pre>Patch Set 1:

Build Started https://jenkins.hyperledger.org/job/fabric-sdk-java-master-verify-x86_64/210/ (2/2)</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 10/21/2019, 1:01:53 PM<br><strong>Message</strong>: <pre>Patch Set 1: Verified-1

Build Failed 

https://jenkins.hyperledger.org/job/fabric-sdk-java-master-verify-1.4-x86_64/217/ : FAILURE

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-sdk-java-master-verify-1.4-x86_64/217

https://jenkins.hyperledger.org/job/fabric-sdk-java-master-verify-x86_64/210/ : FAILURE

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-sdk-java-master-verify-x86_64/210</pre><strong>Reviewer</strong>: Mark S. Lewis - Mark.S.Lewis@outlook.com<br><strong>Reviewed</strong>: 10/22/2019, 11:10:38 AM<br><strong>Message</strong>: <pre>Patch Set 1:

reverify</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 10/22/2019, 11:10:47 AM<br><strong>Message</strong>: <pre>Patch Set 1: -Verified

Build Started https://jenkins.hyperledger.org/job/fabric-sdk-java-master-verify-x86_64/211/ (2/2)</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 10/22/2019, 11:10:47 AM<br><strong>Message</strong>: <pre>Patch Set 1:

Build Started https://jenkins.hyperledger.org/job/fabric-sdk-java-master-verify-1.4-x86_64/218/ (1/2)</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 10/22/2019, 1:10:58 PM<br><strong>Message</strong>: <pre>Patch Set 1: Verified-1

Build Failed 

https://jenkins.hyperledger.org/job/fabric-sdk-java-master-verify-1.4-x86_64/218/ : FAILURE

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-sdk-java-master-verify-1.4-x86_64/218

https://jenkins.hyperledger.org/job/fabric-sdk-java-master-verify-x86_64/211/ : FAILURE

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-sdk-java-master-verify-x86_64/211</pre><strong>Reviewer</strong>: Mark S. Lewis - Mark.S.Lewis@outlook.com<br><strong>Reviewed</strong>: 10/23/2019, 6:38:02 AM<br><strong>Message</strong>: <pre>Patch Set 1: Code-Review-1

It looks like the behaviour following your change will be: if any of the peers we tried to discover from generated an error, the discovery will fail. This will happen regardless of whether or we successfully obtained all the endorsing endpoints.

This seems like it would allow a single faulty peer (either malicious or innocent failure) to effectively cause a denial of service on the clients using discovery in the network.

Is that correct?</pre><strong>Reviewer</strong>: Nao Nishijima - nao.nishijima.xt@hitachi.com<br><strong>Reviewed</strong>: 10/23/2019, 8:21:28 AM<br><strong>Message</strong>: <pre>Patch Set 1:

Thank you for reviewing. Indeed, this is not properly. I will abandon.</pre><strong>Reviewer</strong>: Nao Nishijima - nao.nishijima.xt@hitachi.com<br><strong>Reviewed</strong>: 10/23/2019, 8:21:39 AM<br><strong>Message</strong>: <pre>Abandoned</pre><h1>PatchSets</h1><h3>PatchSet Number: 1</h3><blockquote><strong>Type</strong>: REWORK<br><strong>Author</strong>: Nao Nishijima - nao.nishijima.xt@hitachi.com<br><strong>Uploader</strong>: Nao Nishijima - nao.nishijima.xt@hitachi.com<br><strong>Created</strong>: 10/21/2019, 12:06:01 PM<br><strong>UnmergedRevision</strong>: cfbd0ffb312133d1fdb95cded02f157760512105<br><br><strong>Approver</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Approved</strong>: 10/22/2019, 1:10:58 PM<br><strong>Type</strong>: Verified<br><strong>Value</strong>: -1<br><br><strong>Approver</strong>: Mark S. Lewis - Mark.S.Lewis@outlook.com<br><strong>Approved</strong>: 10/23/2019, 6:38:02 AM<br><strong>Type</strong>: Code-Review<br><strong>Value</strong>: -1<br><br></blockquote>