<strong>Project</strong>: fabric-chaincode-node</br><strong>Branch</strong>: master<br><strong>ID</strong>: 16597<br><strong>Subject</strong>: [FAB-7611] Rethrow the error for invoked chaincode<br><strong>Status</strong>: ABANDONED<br><strong>Owner</strong>: Daan Poron - daan@poron.be<br><strong>Assignee</strong>:<strong>Created</strong>: 1/5/2018, 8:29:24 AM<br><strong>LastUpdated</strong>: 2/13/2018, 11:49:52 AM<br><strong>CommitMessage</strong>:<br><pre>[FAB-7611] Rethrow the error for invoked chaincode

Inside the node.js chaincode when invoked chaincode throws an error
there is no way to catch this error in the calling chaincode. This will
rethrow the error inside the calling chaincode. And this way it will propagate
all the way to the calling client as well.

Change-Id: I1374a2ee98689964c4a25cca6699fa47a0486e46
Signed-off-by: Daan Poron <daan@poron.be>
</pre><h1>Comments</h1><strong>Reviewer</strong>: Daan Poron - daan@poron.be<br><strong>Reviewed</strong>: 1/5/2018, 8:29:24 AM<br><strong>Message</strong>: <pre>Uploaded patch set 1.</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 1/5/2018, 8:29:35 AM<br><strong>Message</strong>: <pre>Patch Set 1:

Build Started https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-s390x/62/ (1/2)</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 1/5/2018, 8:32:22 AM<br><strong>Message</strong>: <pre>Patch Set 1:

Build Started https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-x86_64/120/ (2/2)</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 1/5/2018, 8:47:27 AM<br><strong>Message</strong>: <pre>Patch Set 1: Verified-1

Build Failed 

https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-x86_64/120/ : FAILURE

No problems were identified. If you know why this problem occurred, please add a suitable Cause for it. ( https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-x86_64/120/ )

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-chaincode-node-verify-x86_64/120

https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-s390x/62/ : SUCCESS

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-chaincode-node-verify-s390x/62</pre><strong>Reviewer</strong>: Daan Poron - daan@poron.be<br><strong>Reviewed</strong>: 1/5/2018, 8:58:39 AM<br><strong>Message</strong>: <pre>Patch Set 1:

not sure why the tests are failing ... where can i find the chaincode that's invoked? the thing is that with this change if the chaincodes invokes other chaincode and that chaincode throws an error then the error will be returned to the client while previously this wasn't the case. But to fix this i need to know where the chaincode is and what it is doing?</pre><strong>Reviewer</strong>: Bret Harrison - beharrison@nc.rr.com<br><strong>Reviewed</strong>: 2/5/2018, 4:16:45 PM<br><strong>Message</strong>: <pre>Patch Set 1:

reverify</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 2/5/2018, 4:16:54 PM<br><strong>Message</strong>: <pre>Patch Set 1: -Verified

Build Started https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-s390x/75/ (1/2)</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 2/5/2018, 4:18:29 PM<br><strong>Message</strong>: <pre>Patch Set 1:

Build Started https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-x86_64/129/ (2/2)</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 2/5/2018, 4:31:58 PM<br><strong>Message</strong>: <pre>Patch Set 1: Verified-1

Build Failed 

https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-x86_64/129/ : FAILURE

No problems were identified. If you know why this problem occurred, please add a suitable Cause for it. ( https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-x86_64/129/ )

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-chaincode-node-verify-x86_64/129

https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-s390x/75/ : FAILURE

No problems were identified. If you know why this problem occurred, please add a suitable Cause for it. ( https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-s390x/75/ )

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-chaincode-node-verify-s390x/75</pre><strong>Reviewer</strong>: Dave Kelsey - d_kelsey@uk.ibm.com<br><strong>Reviewed</strong>: 2/6/2018, 3:30:36 AM<br><strong>Message</strong>: <pre>Patch Set 1: Code-Review-1

Please could you add a test case fr this change please.</pre><strong>Reviewer</strong>: Ramesh Babu Thoomu - rameshbabu.thoomu@gmail.com<br><strong>Reviewed</strong>: 2/7/2018, 11:46:13 AM<br><strong>Message</strong>: <pre>Patch Set 1:

reverify-z</pre><strong>Reviewer</strong>: Ramesh Babu Thoomu - rameshbabu.thoomu@gmail.com<br><strong>Reviewed</strong>: 2/7/2018, 11:46:28 AM<br><strong>Message</strong>: <pre>Removed reviewer Ramesh Babu.</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 2/7/2018, 11:46:35 AM<br><strong>Message</strong>: <pre>Patch Set 1: -Verified

Build Started https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-s390x/76/</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 2/7/2018, 11:55:09 AM<br><strong>Message</strong>: <pre>Patch Set 1: Verified+1

Build Successful 

https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-s390x/76/ : SUCCESS

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-chaincode-node-verify-s390x/76</pre><strong>Reviewer</strong>: Ramesh Babu Thoomu - rameshbabu.thoomu@gmail.com<br><strong>Reviewed</strong>: 2/7/2018, 12:07:13 PM<br><strong>Message</strong>: <pre>Patch Set 1:

reverify-x</pre><strong>Reviewer</strong>: Ramesh Babu Thoomu - rameshbabu.thoomu@gmail.com<br><strong>Reviewed</strong>: 2/7/2018, 12:07:20 PM<br><strong>Message</strong>: <pre>Removed reviewer Ramesh Babu.</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 2/7/2018, 12:09:39 PM<br><strong>Message</strong>: <pre>Patch Set 1: -Verified

Build Started https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-x86_64/130/</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 2/7/2018, 12:23:33 PM<br><strong>Message</strong>: <pre>Patch Set 1: Verified+1

Build Successful 

https://jenkins.hyperledger.org/job/fabric-chaincode-node-verify-x86_64/130/ : SUCCESS

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-chaincode-node-verify-x86_64/130</pre><strong>Reviewer</strong>: Dave Kelsey - d_kelsey@uk.ibm.com<br><strong>Reviewed</strong>: 2/13/2018, 11:49:52 AM<br><strong>Message</strong>: <pre>Abandoned

The concept has been merged along with appropriate unit and e2e tests, this change no longer required, but thanks for the CR.</pre><h1>PatchSets</h1><h3>PatchSet Number: 1</h3><blockquote><strong>Type</strong>: REWORK<br><strong>Author</strong>: Daan Poron - daan@poron.be<br><strong>Uploader</strong>: Daan Poron - daan@poron.be<br><strong>Created</strong>: 1515158964<br><strong>UnmergedRevision</strong>: 5ba903c040bfbdc172e681e24c324f718825a119<br><br><strong>Approver</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Approved</strong>: 2/7/2018, 12:23:33 PM<br><strong>Type</strong>: Verified<br><strong>Value</strong>: 1<br><br><strong>Approver</strong>: Dave Kelsey - d_kelsey@uk.ibm.com<br><strong>Approved</strong>: 2/6/2018, 3:30:36 AM<br><strong>Type</strong>: Code-Review<br><strong>Value</strong>: -1<br><br></blockquote>